// file: IbrowOntology.java generated by ontology bean generator.  DO NOT EDIT, UNLESS YOU ARE REALLY SURE WHAT YOU ARE DOING!
package darbdavys;

import jade.content.onto.*;
import jade.content.schema.*;

/** file: IbrowOntology.java
 * @author ontology bean generator
 * @version 2019/05/18, 11:59:16
 */
public class IbrowOntology extends jade.content.onto.Ontology  {

  private static final long serialVersionUID = 7030251501279179338L;

  //NAME
  public static final String ONTOLOGY_NAME = "ibrow";
  // The singleton instance of this ontology
  private static Ontology theInstance = new IbrowOntology();
  public static Ontology getInstance() {
     return theInstance;
  }


   // VOCABULARY
    public static final String SIMPLEPRANESIMAS_PRANESIMAS="Pranesimas";
    public static final String SIMPLEPRANESIMAS="SimplePranesimas";
    public static final String PAIESKA_PAGAL_DARBDAVI_PAIESKAPAGALDARBDAVIDAUG="PaieskaPagalDarbdaviDaug";
    public static final String PAIESKA_PAGAL_DARBDAVI="Paieska_pagal_darbdavi";
    public static final String PAIESKA_MSG_DARBUOTOJO_PAIESKA_MSG="Darbuotojo_paieska_msg";
    public static final String PAIESKA_MSG="Paieska_msg";
    public static final String IMONES_INFO_VADOVAS="Vadovas";
    public static final String IMONES_INFO_GID="GID";
    public static final String IMONES_INFO_DARBAS="Darbas";
    public static final String IMONES_INFO_PAVADINIMAS="Pavadinimas";
    public static final String IMONES_INFO="Imones_Info";
    public static final String IMONES_INFO_DAUG_IMONES_INFO_VIENETAS="Imones_Info_Vienetas";
    public static final String IMONES_INFO_DAUG="Imones_Info_Daug";
    public static final String DARBO_INFO_DAUG_DARBO_INFO_VIENETAS="Darbo_Info_Vienetas";
    public static final String DARBO_INFO_DAUG="Darbo_Info_Daug";
    public static final String DARBO_INFO_REIKALINGAS_STAZAS="Reikalingas_Stazas";
    public static final String DARBO_INFO_ATLYGINIMAS="Atlyginimas";
    public static final String DARBO_INFO_MIESTAS="Miestas";
    public static final String DARBO_INFO_ID="ID";
    public static final String DARBO_INFO_VALANDOS="Valandos";
    public static final String DARBO_INFO_POZICIJA="Pozicija";
    public static final String DARBO_INFO="Darbo_Info";
    public static final String VISISIULOMIDARBAI_VISIPASIULYMAI="visiPasiulymai";
    public static final String VISISIULOMIDARBAI="VisiSiulomiDarbai";
    public static final String DARBUOTOJOPAIESKA_LINE_ATLYGINIMAS="Atlyginimas";
    public static final String DARBUOTOJOPAIESKA_LINE_REIKALINGAS_STAZAS="Reikalingas_stazas";
    public static final String DARBUOTOJOPAIESKA_LINE_MIESTAS="Miestas";
    public static final String DARBUOTOJOPAIESKA_LINE_POZICIJA="Pozicija";
    public static final String DARBUOTOJOPAIESKA_LINE="DarbuotojoPaieska_line";

  /**
   * Constructor
  */
  private IbrowOntology(){ 
    super(ONTOLOGY_NAME, BasicOntology.getInstance());
    try { 

    // adding Concept(s)
    ConceptSchema darbuotojoPaieska_lineSchema = new ConceptSchema(DARBUOTOJOPAIESKA_LINE);
    add(darbuotojoPaieska_lineSchema, darbdavys.DarbuotojoPaieska_line.class);
    ConceptSchema visiSiulomiDarbaiSchema = new ConceptSchema(VISISIULOMIDARBAI);
    add(visiSiulomiDarbaiSchema, darbdavys.VisiSiulomiDarbai.class);
    ConceptSchema darbo_InfoSchema = new ConceptSchema(DARBO_INFO);
    add(darbo_InfoSchema, darbdavys.Darbo_Info.class);
    ConceptSchema darbo_Info_DaugSchema = new ConceptSchema(DARBO_INFO_DAUG);
    add(darbo_Info_DaugSchema, darbdavys.Darbo_Info_Daug.class);
    ConceptSchema imones_Info_DaugSchema = new ConceptSchema(IMONES_INFO_DAUG);
    add(imones_Info_DaugSchema, darbdavys.Imones_Info_Daug.class);
    ConceptSchema imones_InfoSchema = new ConceptSchema(IMONES_INFO);
    add(imones_InfoSchema, darbdavys.Imones_Info.class);

    // adding AgentAction(s)

    // adding AID(s)

    // adding Predicate(s)
    PredicateSchema paieska_msgSchema = new PredicateSchema(PAIESKA_MSG);
    add(paieska_msgSchema, darbdavys.Paieska_msg.class);
    PredicateSchema paieska_pagal_darbdaviSchema = new PredicateSchema(PAIESKA_PAGAL_DARBDAVI);
    add(paieska_pagal_darbdaviSchema, darbdavys.Paieska_pagal_darbdavi.class);
    PredicateSchema simplePranesimasSchema = new PredicateSchema(SIMPLEPRANESIMAS);
    add(simplePranesimasSchema, darbdavys.SimplePranesimas.class);


    // adding fields
    darbuotojoPaieska_lineSchema.add(DARBUOTOJOPAIESKA_LINE_POZICIJA, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    darbuotojoPaieska_lineSchema.add(DARBUOTOJOPAIESKA_LINE_MIESTAS, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    darbuotojoPaieska_lineSchema.add(DARBUOTOJOPAIESKA_LINE_REIKALINGAS_STAZAS, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    darbuotojoPaieska_lineSchema.add(DARBUOTOJOPAIESKA_LINE_ATLYGINIMAS, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    visiSiulomiDarbaiSchema.add(VISISIULOMIDARBAI_VISIPASIULYMAI, darbo_Info_DaugSchema, 1, ObjectSchema.UNLIMITED);
    darbo_InfoSchema.add(DARBO_INFO_POZICIJA, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    darbo_InfoSchema.add(DARBO_INFO_VALANDOS, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    darbo_InfoSchema.add(DARBO_INFO_ID, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    darbo_InfoSchema.add(DARBO_INFO_MIESTAS, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    darbo_InfoSchema.add(DARBO_INFO_ATLYGINIMAS, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    darbo_InfoSchema.add(DARBO_INFO_REIKALINGAS_STAZAS, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    darbo_Info_DaugSchema.add(DARBO_INFO_DAUG_DARBO_INFO_VIENETAS, darbo_InfoSchema, 1, ObjectSchema.UNLIMITED);
    imones_Info_DaugSchema.add(IMONES_INFO_DAUG_IMONES_INFO_VIENETAS, imones_InfoSchema, 1, ObjectSchema.UNLIMITED);
    imones_InfoSchema.add(IMONES_INFO_PAVADINIMAS, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    imones_InfoSchema.add(IMONES_INFO_DARBAS, darbo_InfoSchema, 1, ObjectSchema.UNLIMITED);
    imones_InfoSchema.add(IMONES_INFO_GID, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    imones_InfoSchema.add(IMONES_INFO_VADOVAS, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    paieska_msgSchema.add(PAIESKA_MSG_DARBUOTOJO_PAIESKA_MSG, darbuotojoPaieska_lineSchema, 1, ObjectSchema.UNLIMITED);
    paieska_pagal_darbdaviSchema.add(PAIESKA_PAGAL_DARBDAVI_PAIESKAPAGALDARBDAVIDAUG, imones_Info_DaugSchema, 1, ObjectSchema.UNLIMITED);
    simplePranesimasSchema.add(SIMPLEPRANESIMAS_PRANESIMAS, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);

    // adding name mappings

    // adding inheritance

   }catch (java.lang.Exception e) {e.printStackTrace();}
  }
}
